version: '3.9'

services:
  # reverse proxy

  pauliceia_nginx:
    container_name: pauliceia_nginx
    image: nginx:1.19.5
    # restart: always
    env_file:
      - ./env_files/nginx.env
    volumes:
      - ./volumes/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./volumes/nginx/include:/etc/nginx/conf.d/include
    # volumes:
    #   - ./templates:/etc/nginx/templates
    networks:
      - pauliceia
    depends_on:
      - pauliceia_vgimws
      - pauliceia_portainer
    ports:
      - 8080:80

  # pauliceia services - 300x

  pauliceia_vgimws:
    container_name: pauliceia_vgimws
    image: pauliceia/api-vgiws:0.0.7
    # command: python -u main.py
    command: python -u main.py --debug=True --publish_layers_in_geoserver=False
    # restart: always
    # env_file:
    #   - ./env_files/vgimws.env
    volumes:
      - ../vgiws:/usr/src/vgiws
    depends_on:
      - pauliceia_pgadmin4
    networks:
      - pauliceia
    ports:
      - 3001:8888

  # pauliceia database - 400x

  pauliceia_pgadmin4:
    container_name: pauliceia_pgadmin4
    image: dpage/pgadmin4:4.15
    # restart: always
    env_file:
      - ./env_files/pgadmin4.env
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    networks:
      - pauliceia
    depends_on:
      - pauliceia_postgis
    ports:
      - 4000:80

  pauliceia_postgis:
    container_name: pauliceia_postgis
    # image: kartoza/postgis:11.0-2.5
    image: kartoza/postgis:13.0
    # restart: always
    env_file:
      - ./env_files/postgis.env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    networks:
      - pauliceia
    # ports:
    #   - 4001:5432

  # extra services - 900x

  pauliceia_portainer:
    container_name: pauliceia_portainer
    image: portainer/portainer:1.24.1-alpine
    # restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pauliceia
    ports:
      - 9000:9000

volumes:
  portainer_data:

networks:
  pauliceia:
    driver: bridge
