version: '3'

services:
  # reverse proxy service

  pauliceia_nginx:
    container_name: pauliceia_nginx
    image: nginx:1.17.6
    # restart: always
    volumes:
      - ../edit:/var/www/html/edit
      - ./volumes/nginx/nginx.dev.template:/etc/nginx/conf.d/mysite.template
      # - ../config/files-conf-local/nginx/app.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./env_files/nginx.env
    depends_on:
      - pauliceia_postgis
      - pauliceia_pgadmin4
      - pauliceia_vgimws
      - pauliceia_geocoding
      - pauliceia_geoserver_rest
      - pauliceia_edit
      - pauliceia_portainer
      - pauliceia_geoserver
      - pauliceia_tomcat
    networks:
      - pauliceia
    ports:
      - 80:80

  # database services

  pauliceia_postgis:
    container_name: pauliceia_postgis
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    env_file:
      - ./env/postgis.env
    networks:
      - pauliceia
    ports:
      - 9000:5432

  pauliceia_pgadmin4:
    container_name: pauliceia_pgadmin4
    image: dpage/pgadmin4:4.14
    # restart: always
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    env_file:
      - ./env/pgadmin4.env
    depends_on:
      - pauliceia_postgis
    networks:
      - pauliceia
    ports:
      - 9001:80
    # http://localhost:9001/

  # pauliceia services

  pauliceia_vgimws:
    container_name: pauliceia_vgimws
    image: pauliceia/api-vgiws:0.0.2
    # command: python -u main.py
    command: python -u main.py --debug=True --publish_layers_in_geoserver=False
    # restart: always
    volumes:
      - ../vgiws:/usr/src/vgiws
    # env_file:
    #   - ./env_files/vgimws.env
    depends_on:
      - pauliceia_postgis
    networks:
      - pauliceia
    ports:
      - 9010:8888

  pauliceia_geocoding:
    container_name: pauliceia_geocoding
    image: pauliceia/api-geocoding
    # restart: always
    volumes:
      - ../GeocodingAPI:/usr/src/geocoding
    env_file:
      - ./env/geocoding.env
    depends_on:
      - pauliceia_postgis
    networks:
      - pauliceia
    ports:
      - 9011:3000

  pauliceia_geoserver_rest:
    container_name: pauliceia_geoserver_rest
    image: pauliceia/api-geoserver
    # restart: always
    volumes:
      - ../geoserver-rest:/usr/src/geoserver-rest
    depends_on:
      - pauliceia_postgis
    networks:
      - pauliceia
    # ports:
    #   - 9012:3000

  pauliceia_edit:
    container_name: pauliceia_edit
    image: pauliceia/php-webeditor
    # restart: always
    volumes:
      # - /var/www/html/edit:/var/www/html/edit
      - ../edit:/var/www/html/edit
    depends_on:
      - pauliceia_postgis
    networks:
      - pauliceia
    ports:
      - 9013:8000

  # third party services

  pauliceia_portainer:
    container_name: pauliceia_portainer
    image: portainer/portainer:1.23.0
    # restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./env_files/portainer.env
    networks:
      - pauliceia
    ports:
      - 9020:9000

  pauliceia_geoserver:
    container_name: pauliceia_geoserver
    image: kartoza/geoserver:2.15.2
    # restart: always
    volumes:
      - ./volumes/geoserver/data_app:/opt/geoserver/data_dir
      - ./volumes/geoserver/shapefiles:/opt/geoserver/shapefiles
      # - ./volumes/geoserver/shapefiles:/home/geoserver/shapefiles
      - ./volumes/geoserver/conf-geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./volumes/geoserver/conf-geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env_files/geoserver.env
    networks:
      - pauliceia
    ports:
      - 9021:9000

  pauliceia_tomcat:
    container_name: pauliceia_tomcat
    image: tomcat:9.0.20-jre8
    # restart: always
    # volumes:
    #   - ./volumes/tomcat:/usr/local/tomcat/conf
    # env_file:
    #   - ./env_files/tomcat.env
    networks:
      - pauliceia
    ports:
      - 9022:8080

volumes:
  portainer_data:

networks:
  pauliceia:
    driver: bridge
